/*
	Mod Support | Religion Expanded
	Authors: ChimpanG
*/

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------

UPDATE	ModifierArguments
SET		Value = 3
WHERE	Name = 'Amount'
AND		ModifierId
IN		(
		'MODIFIER_CSE_RELIGIOUS_ATASHKADEH_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_POSEIDONION_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_SATURNIUM_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_MINERVIUM_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_SERAPEUM_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_SURAU_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_PRIORY_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_CHAPEL_FAITH_MOD'
		);

-----------------------------------------------
-- ModifierStrings
-----------------------------------------------

UPDATE	ModifierStrings
SET		Text = 'LOC_CSE_RELIGIOUS_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS'
WHERE	ModifierId IN (
		'MODIFIER_CSE_RELIGIOUS_ATASHKADEH_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_POSEIDONION_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_SATURNIUM_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_MINERVIUM_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_SERAPEUM_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_SURAU_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_PRIORY_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_CHAPEL_FAITH_MOD'
		);