/*
	Icons
	Authors: ChimpanG
*/

-----------------------------------------------
-- IconTextureAtlases
-----------------------------------------------
	
INSERT INTO IconTextureAtlases	
		(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Baseline,	Filename								)
VALUES  -- Types
		('ICON_ATLAS_CSE_TYPES_ATLAS',			22,	 		8,				1,				0,			'CSE_TYPES_ATLAS_22.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS',			30, 		8,				1,				0,			'CSE_TYPES_ATLAS_30.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS',			36, 		8,				1,				0,			'CSE_TYPES_ATLAS_36.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS',			40, 		8,				1,				0,			'CSE_TYPES_ATLAS_40.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS',			44, 		8,				1,				0,			'CSE_TYPES_ATLAS_44.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS',			48, 		8,				1,				0,			'CSE_TYPES_ATLAS_48.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS',			64, 		8,				1,				0,			'CSE_TYPES_ATLAS_64.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS',			68, 		8,				1,				0,			'CSE_TYPES_ATLAS_68.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS',			80, 		8,				1,				0,			'CSE_TYPES_ATLAS_80.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS',			256, 		8,				1,				0,			'CSE_TYPES_ATLAS_256.dds'				),
		('ICON_ATLAS_CSE_TYPES_ATLAS_ENVOY',	26, 		8,				1,				0,			'CSE_TYPES_ENVOY_ATLAS_26.dds'			),
		('ICON_ATLAS_CSE_TYPES_ATLAS_ENVOY',	50, 		8,				1,				0,			'CSE_TYPES_ENVOY_ATLAS_50.dds'			),

		-- City-States
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS',		256,	 	8,				8,				0,			'CSE_CITYSTATES_ATLAS_256.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS',		80,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_80.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS',		64,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_64.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS',		50,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_50.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS',		48,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_48.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS',		44,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_44.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS',		36,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_36.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS',		30,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_30.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS',		22,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_22.dds'			),

		('ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	256,	 	8,				8,				0,			'CSE_CITYSTATES_ATLAS_B_256.dds'		),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	80,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_B_80.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	64,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_B_64.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	50,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_B_50.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	48,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_B_48.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	44,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_B_44.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	36,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_B_36.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	30,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_B_30.dds'			),
		('ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	22,			8,				8,				0,			'CSE_CITYSTATES_ATLAS_B_22.dds'			),

		-- Resources
		('ICON_ATLAS_CSE_RESOURCES_ATLAS',		256,	 	8,				2,				0,			'CSE_RESOURCES_ATLAS_256.dds'			),
		('ICON_ATLAS_CSE_RESOURCES_ATLAS',		64,		 	8,				2,				0,			'CSE_RESOURCES_ATLAS_64.dds'			),
		('ICON_ATLAS_CSE_RESOURCES_ATLAS',		50,		 	8,				2,				0,			'CSE_RESOURCES_ATLAS_50.dds'			),
		('ICON_ATLAS_CSE_RESOURCES_ATLAS',		38,		 	8,				2,				0,			'CSE_RESOURCES_ATLAS_38.dds'			),
		('ICON_ATLAS_CSE_RESOURCES_ATLAS',		22,		 	8,				2,				6,			'CSE_RESOURCES_ATLAS_22.dds'			),

		-- Improvements
		('ICON_ATLAS_CSE_IMPROVEMENTS_ATLAS',	256,	 	8,				1,				0,			'CVS_CityStates_Improvements256.dds'	),
		('ICON_ATLAS_CSE_IMPROVEMENTS_ATLAS',	80,			8,				1,				0,			'CVS_CityStates_Improvements80.dds'		),
		('ICON_ATLAS_CSE_IMPROVEMENTS_ATLAS',	50,			8,				1,				0,			'CVS_CityStates_Improvements50.dds'		),
		('ICON_ATLAS_CSE_IMPROVEMENTS_ATLAS',	40,			8,				1,				0,			'CVS_CityStates_Improvements40.dds'		),
		('ICON_ATLAS_CSE_IMPROVEMENTS_ATLAS',	38,		 	8,				1,				0,			'CVS_CityStates_Improvements38.dds'		);

-----------------------------------------------
-- IconDefinitions
-----------------------------------------------

DELETE FROM IconDefinitions WHERE Name IN ('ICON_CITYSTATE_INDUSTRIAL', 'ICON_ENVOY_BONUS_INDUSTRIAL', 'ICON_CITYSTATE_MILITARISTIC', 'ICON_ENVOY_BONUS_MILITARISTIC');

INSERT INTO IconDefinitions	
		(Name,									Atlas, 									'Index'	)
VALUES	-- Types
		('ICON_CITYSTATE_INDUSTRIAL',			'ICON_ATLAS_CSE_TYPES_ATLAS',			0		),
		('ICON_CITYSTATE_MILITARISTIC',			'ICON_ATLAS_CSE_TYPES_ATLAS',			1		),
		('ICON_CITYSTATE_CSE_AGRICULTURAL',		'ICON_ATLAS_CSE_TYPES_ATLAS',			2		),
		('ICON_CITYSTATE_CSE_ENTERTAINMENT',	'ICON_ATLAS_CSE_TYPES_ATLAS',			3		),
		('ICON_CITYSTATE_CSE_CONSULAR',			'ICON_ATLAS_CSE_TYPES_ATLAS',			4		),
		('ICON_CITYSTATE_CSE_MARITIME',			'ICON_ATLAS_CSE_TYPES_ATLAS',			5		),

		('ICON_ENVOY_BONUS_INDUSTRIAL',			'ICON_ATLAS_CSE_TYPES_ATLAS_ENVOY',		1		),
		('ICON_ENVOY_BONUS_MILITARISTIC',		'ICON_ATLAS_CSE_TYPES_ATLAS_ENVOY',		0		),
		('ICON_ENVOY_BONUS_CSE_AGRICULTURAL',	'ICON_ATLAS_CSE_TYPES_ATLAS_ENVOY',		2		),
		('ICON_ENVOY_BONUS_CSE_ENTERTAINMENT',	'ICON_ATLAS_CSE_TYPES_ATLAS_ENVOY',		3		),
		('ICON_ENVOY_BONUS_CSE_CONSULAR',		'ICON_ATLAS_CSE_TYPES_ATLAS_ENVOY',		4		),
		('ICON_ENVOY_BONUS_CSE_MARITIME',		'ICON_ATLAS_CSE_TYPES_ATLAS_ENVOY',		5		),

		-- City-States
		('ICON_CIVILIZATION_CSE_ALAMUT',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		0		),
		('ICON_CIVILIZATION_CSE_AMPI',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		1		),
		('ICON_CIVILIZATION_CSE_ANURADHAPURA',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		2		),
		('ICON_CIVILIZATION_CSE_AYNUK',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		3		),
		('ICON_CIVILIZATION_CSE_AZCAPOTZALCO',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		4		),
		('ICON_CIVILIZATION_CSE_BAIAE',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		5		),
		('ICON_CIVILIZATION_CSE_BEIKTHANO',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		6		),
		('ICON_CIVILIZATION_CSE_BUTUAN',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		7		),
		('ICON_CIVILIZATION_CSE_CATALHOYUK',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		8		),
		('ICON_CIVILIZATION_CSE_CHAN_CHAN',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		9		),
		('ICON_CIVILIZATION_CSE_CHETRO_KETL',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		10		),
		('ICON_CIVILIZATION_CSE_DAKAR',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		11		),
		('ICON_CIVILIZATION_CSE_DELOS',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		12		),
		('ICON_CIVILIZATION_CSE_DELPHI',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		13		),
		('ICON_CIVILIZATION_CSE_DJIBOUTI',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		14		),
		('ICON_CIVILIZATION_CSE_DODONA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		15		),
		('ICON_CIVILIZATION_CSE_ETZANOA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		16		),
		('ICON_CIVILIZATION_CSE_GARAMA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		17		),
		('ICON_CIVILIZATION_CSE_GOBEKLI_TEPE',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		18		),
		('ICON_CIVILIZATION_CSE_GUNDESHAPUR',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		19		),
		('ICON_CIVILIZATION_CSE_HADAD',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		20		),
		('ICON_CIVILIZATION_CSE_HALIN',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		21		),
		('ICON_CIVILIZATION_CSE_HAVANA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		22		),
		('ICON_CIVILIZATION_CSE_HAZOR',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		23		),
		('ICON_CIVILIZATION_CSE_HORMUZ',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		24		),
		('ICON_CIVILIZATION_CSE_HVALSEY',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		25		),
		('ICON_CIVILIZATION_CSE_IQALUIT',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		26		),
		('ICON_CIVILIZATION_CSE_IZAPA',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		27		),
		('ICON_CIVILIZATION_CSE_JOHANNESBURG',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		28		),
		('ICON_CIVILIZATION_CSE_JOLO',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		29		),
		('ICON_CIVILIZATION_CSE_KADESH',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		30		),
		('ICON_CIVILIZATION_CSE_KANNAUJ',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		31		),
		('ICON_CIVILIZATION_CSE_KATARAGAMA',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		32		),
		('ICON_CIVILIZATION_CSE_KELANIYA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		33		),
		('ICON_CIVILIZATION_CSE_KUHIKUGU',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		34		),
		('ICON_CIVILIZATION_CSE_LIMA',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		35		),
		('ICON_CIVILIZATION_CSE_MACAU',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		36		),
		('ICON_CIVILIZATION_CSE_MAI',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		37		),
		('ICON_CIVILIZATION_CSE_MAINGMAW',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		38		),
--		('ICON_CIVILIZATION_CSE_MARRAKECH',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		39		),
		('ICON_CIVILIZATION_CSE_MEGIDDO',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		40		),
		('ICON_CIVILIZATION_CSE_MEHRGARH',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		41		),
		('ICON_CIVILIZATION_CSE_MOMBASA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		42		),
		('ICON_CIVILIZATION_CSE_MONACO',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		43		),
		('ICON_CIVILIZATION_CSE_MZIZIMA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		44		),
		('ICON_CIVILIZATION_CSE_NALANDA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		45		),
		('ICON_CIVILIZATION_CSE_NASSAU',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		46		),
		('ICON_CIVILIZATION_CSE_PALMYRA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		47		),
		('ICON_CIVILIZATION_CSE_PORT_ROYAL',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		48		),
		('ICON_CIVILIZATION_CSE_QATNA',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		49		),
		('ICON_CIVILIZATION_CSE_SALE',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		50		),
		('ICON_CIVILIZATION_CSE_SAMARQAND',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		51		),
		('ICON_CIVILIZATION_CSE_SANAA',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		52		),
		('ICON_CIVILIZATION_CSE_SEUTHOPOLIS',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		53		),
		('ICON_CIVILIZATION_CSE_SHAHR_E_SUKHTE','ICON_ATLAS_CSE_CITYSTATES_ATLAS',		54		),
		('ICON_CIVILIZATION_CSE_SIDON',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		55		),
		('ICON_CIVILIZATION_CSE_SINGAPORE',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		56		),
		('ICON_CIVILIZATION_CSE_SRI_KSETRA',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		57		),
		('ICON_CIVILIZATION_CSE_TANGIER',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		58		),
		('ICON_CIVILIZATION_CSE_TAOS',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		59		),
		('ICON_CIVILIZATION_CSE_TEYUNA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		60		),
		('ICON_CIVILIZATION_CSE_TISSAMAHARAMA',	'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		61		),
		('ICON_CIVILIZATION_CSE_TUNERIUT',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		62		),
		('ICON_CIVILIZATION_CSE_UGARIT',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS',		63		),
		('ICON_CIVILIZATION_CSE_URGENCH',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	0		),
		('ICON_CIVILIZATION_CSE_VADUZ',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	1		),
		('ICON_CIVILIZATION_CSE_VALABHI',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	2		),
		('ICON_CIVILIZATION_CSE_VIENNA',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	3		),
		('ICON_CIVILIZATION_CSE_WYAM',			'ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	4		),
		('ICON_CIVILIZATION_CSE_PHASIS',		'ICON_ATLAS_CSE_CITYSTATES_ATLAS_B',	6		),
		
		-- Improvements
		('ICON_IMPROVEMENT_CSE_DAGOBA',			'ICON_ATLAS_CSE_IMPROVEMENTS_ATLAS',	1		),
		('ICON_IMPROVEMENT_CSE_KIVA',			'ICON_ATLAS_CSE_IMPROVEMENTS_ATLAS',	0		),
--		('ICON_IMPROVEMENT_CSE_RIAD',			'ICON_ATLAS_CSE_IMPROVEMENTS_ATLAS',	2		),

		-- Resources
		('ICON_RESOURCE_CSE_ABACA',				'ICON_ATLAS_CSE_RESOURCES_ATLAS',		0		),
		('RESOURCE_CSE_ABACA',					'ICON_ATLAS_CSE_RESOURCES_ATLAS',		0		),
		('ICON_RESOURCE_CSE_BEESWAX',			'ICON_ATLAS_CSE_RESOURCES_ATLAS',		1		),
		('RESOURCE_CSE_BEESWAX',				'ICON_ATLAS_CSE_RESOURCES_ATLAS',		1		),
		('ICON_RESOURCE_CSE_BETEL_NUT',			'ICON_ATLAS_CSE_RESOURCES_ATLAS',		2		),
		('RESOURCE_CSE_BETEL_NUT',				'ICON_ATLAS_CSE_RESOURCES_ATLAS',		2		),
		('ICON_RESOURCE_CSE_GLASS',				'ICON_ATLAS_CSE_RESOURCES_ATLAS',		3		),
		('RESOURCE_CSE_GLASS',					'ICON_ATLAS_CSE_RESOURCES_ATLAS',		3		),
		('ICON_RESOURCE_CSE_LEATHER',			'ICON_ATLAS_CSE_RESOURCES_ATLAS',		4		),
		('RESOURCE_CSE_LEATHER',				'ICON_ATLAS_CSE_RESOURCES_ATLAS',		4		),
		('ICON_RESOURCE_CSE_MANGOSTEEN',		'ICON_ATLAS_CSE_RESOURCES_ATLAS',		5		),
		('RESOURCE_CSE_MANGOSTEEN',				'ICON_ATLAS_CSE_RESOURCES_ATLAS',		5		),
		('ICON_RESOURCE_CSE_SALMON',			'ICON_ATLAS_CSE_RESOURCES_ATLAS',		6		),
		('RESOURCE_CSE_SALMON',					'ICON_ATLAS_CSE_RESOURCES_ATLAS',		6		),
		('ICON_RESOURCE_CSE_WALRUS',			'ICON_ATLAS_CSE_RESOURCES_ATLAS',		8		),
		('RESOURCE_CSE_WALRUS',					'ICON_ATLAS_CSE_RESOURCES_ATLAS',		8		),
		('ICON_RESOURCE_CSE_WOOL',				'ICON_ATLAS_CSE_RESOURCES_ATLAS',		7		),
		('RESOURCE_CSE_WOOL',					'ICON_ATLAS_CSE_RESOURCES_ATLAS',		7		);