/*
	Localisation XP2
	Authors: ChimpanG
*/

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES	

-----------------------------------------------
-- Consular
-----------------------------------------------

	("en_US",	"LOC_CSE_CONSULAR_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS",		"+1 [ICON_FAVOR] Diplomatic Favor in any first-tier Government Plaza building."	),
	("en_US",	"LOC_CSE_CONSULAR_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS",	"+3 [ICON_FAVOR] Diplomatic Favor in any third-tier Government Plaza building."	),

	("en_US",	"LOC_CSE_CONSULAR_TRAIT_MEKONG_DESCRIPTION",				"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_CONSULAR_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_CONSULAR_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_CONSULAR_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_CONSULAR_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS}"	);