/*
	Localisation
	Authors: ChimpanG
*/

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES	

-----------------------------------------------
-- Scientific
-----------------------------------------------

	("en_US",	"LOC_CSE_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS",		"+1 [ICON_SCIENCE] Science in every Library."	),
	("en_US",	"LOC_CSE_SCIENTIFIC_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS",		"+3 [ICON_SCIENCE] Science in every Research Lab."	),

	("en_US",	"LOC_CSE_SCIENTIFIC_TRAIT_MEKONG_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_SCIENTIFIC_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_SCIENTIFIC_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_SCIENTIFIC_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_SCIENTIFIC_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS}"	),

-----------------------------------------------
-- Cultural
-----------------------------------------------

	("en_US",	"LOC_CSE_CULTURAL_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS",			"+1 [ICON_CULTURE] Culture in every Amphitheater."	),
	("en_US",	"LOC_CSE_CULTURAL_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS",		"+3 [ICON_CULTURE] Culture in every Broadcast Center."	),
	
	("en_US",	"LOC_CSE_CULTURAL_TRAIT_MEKONG_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_CULTURAL_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_CULTURAL_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_CULTURAL_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_CULTURAL_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS}"	),

-----------------------------------------------
-- Trade
-----------------------------------------------
	
	("en_US",	"LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS",			"+2 [ICON_GOLD] Gold in every Market or Lighthouse."	),
	("en_US",	"LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS_ALT",		"+2 [ICON_GOLD] Gold in every Market."	),
	("en_US",	"LOC_CSE_TRADE_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS",			"+6 [ICON_GOLD] Gold in every Stock Exchange or Seaport."	),
	("en_US",	"LOC_CSE_TRADE_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS_ALT",		"+6 [ICON_GOLD] Gold in every Stock Exchange."	),
	
	("en_US",	"LOC_CSE_TRADE_TRAIT_MEKONG_DESCRIPTION",						"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS}"	),
	("en_US",	"LOC_CSE_TRADE_TRAIT_MEKONG_DESCRIPTION_ALT",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS_ALT}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_LARGE_INFLUENCE_BONUS_ALT}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_TRADE_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS_ALT}"	),

-----------------------------------------------
-- Religious
-----------------------------------------------

	("en_US",	"LOC_CSE_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS",		"+1 [ICON_FAITH] Faith in every Shrine."	),
	("en_US",	"LOC_CSE_RELIGIOUS_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS",		"+3 [ICON_FAITH] Faith in every Worship building."	),
	
	("en_US",	"LOC_CSE_RELIGIOUS_TRAIT_MEKONG_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS}"	),
	
-----------------------------------------------
-- Militaristic
-----------------------------------------------	
	
	("en_US",	"LOC_CSE_MILITARISTIC_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS",		"+1 [ICON_PRODUCTION] Production towards units in every city with a Barracks or Stable."	),
	("en_US",	"LOC_CSE_MILITARISTIC_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS",	"+3 [ICON_PRODUCTION] Production towards units in every city with a Military Academy."	),
	
	("en_US",	"LOC_CSE_MILITARISTIC_TRAIT_MEKONG_DESCRIPTION",				"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_RELIGIOUS_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS}"	),

-----------------------------------------------
-- Industrial
-----------------------------------------------

	("en_US",	"LOC_CSE_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS",		"+1 [ICON_PRODUCTION] Production towards districts and buildings in every city with a Workshop."	),
	("en_US",	"LOC_CSE_INDUSTRIAL_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS",		"+3 [ICON_PRODUCTION] Production towards districts and buildings in every city with a Power Plant."	),

	("en_US",	"LOC_CSE_INDUSTRIAL_TRAIT_MEKONG_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_INDUSTRIAL_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_INDUSTRIAL_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_INDUSTRIAL_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_INDUSTRIAL_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS}"	),
	
-----------------------------------------------
-- Agrarian
-----------------------------------------------

	("en_US",	"LOC_CSE_AGRICULTURAL_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS",		"+1 [ICON_FOOD] Food in every Granary."		),
	("en_US",	"LOC_CSE_AGRICULTURAL_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS",	"+3 [ICON_FOOD] Food in every Aqueduct."	),

	("en_US",	"LOC_CSE_AGRICULTURAL_TRAIT_MEKONG_DESCRIPTION",				"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_AGRICULTURAL_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_AGRICULTURAL_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_AGRICULTURAL_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_AGRICULTURAL_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS}"	),

-----------------------------------------------
-- Maritime
-----------------------------------------------

	("en_US",	"LOC_CSE_MARITIME_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS",			"+1 [ICON_FOOD] Food in every Lighthouse."															),
	("en_US",	"LOC_CSE_MARITIME_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS",		"+1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production and +2 [ICON_GOLD] Gold in every Seaport."	),

	("en_US",	"LOC_CSE_MARITIME_TRAIT_MEKONG_DESCRIPTION",					"{LOC_MINOR_CIV_SMALL_INFLUENCE_ENVOYS} {LOC_CSE_MARITIME_TRAIT_SMALL_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_MEDIUM_INFLUENCE_ENVOYS} {LOC_CSE_MARITIME_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGE_INFLUENCE_ENVOYS} {LOC_CSE_MARITIME_TRAIT_LARGE_INFLUENCE_BONUS}[NEWLINE]{LOC_MINOR_CIV_LARGEST_INFLUENCE_ENVOYS} {LOC_CSE_MARITIME_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS}"	);