/*
	Types
	Authors: ChimpanG
*/

-----------------------------------------------
-- CSE_ClassTypes
-----------------------------------------------

UPDATE	CSE_ClassTypes
SET		MediumBonus = 'LOC_CSE_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS',
		LargestBonus = 'LOC_CSE_RELIGIOUS_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS',
		TraitDescription = 'LOC_CSE_RELIGIOUS_TRAIT_MEKONG_DESCRIPTION'
WHERE	Type IN ('RELIGIOUS');

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------

UPDATE	ModifierArguments
SET		Value = 1
WHERE	Name = 'Amount'
AND		ModifierId IN ('MODIFIER_CSE_RELIGIOUS_SHRINE_FAITH_MOD');

UPDATE	ModifierArguments
SET		Value = 3
WHERE	Name = 'Amount'
AND		ModifierId
IN		(
		'MODIFIER_CSE_RELIGIOUS_CATHEDRAL_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_DAR_E_MEHR_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_GURDWARA_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_MEETING_HOUSE_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_MOSQUE_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_PAGODA_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_STUPA_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_SYNAGOGUE_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_WAT_FAITH_MOD'
		);

-----------------------------------------------
-- ModifierStrings
-----------------------------------------------

UPDATE	ModifierStrings
SET		Text = 'LOC_CSE_RELIGIOUS_TRAIT_MEDIUM_INFLUENCE_MEKONG_BONUS'
WHERE	ModifierId IN ('MODIFIER_CSE_RELIGIOUS_SHRINE_FAITH');

UPDATE	ModifierStrings
SET		Text = 'LOC_CSE_RELIGIOUS_TRAIT_LARGEST_INFLUENCE_MEKONG_BONUS'
WHERE	ModifierId IN (
		'MODIFIER_CSE_RELIGIOUS_CATHEDRAL_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_DAR_E_MEHR_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_GURDWARA_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_MEETING_HOUSE_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_MOSQUE_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_PAGODA_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_STUPA_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_SYNAGOGUE_FAITH_MOD',
		'MODIFIER_CSE_RELIGIOUS_WAT_FAITH_MOD'
		);