/*
	StartBiases
	Authors: ChimpanG
*/

-----------------------------------------------
-- Schema
-----------------------------------------------

CREATE TABLE IF NOT EXISTS CSE_StartBias
	(
	CityState			TEXT		NOT NULL,
	CivilizationType	TEXT		DEFAULT NULL,
	New					BOOLEAN		DEFAULT 1,
	Type				TEXT		NOT NULL, 
	Object				TEXT		DEFAULT NULL, 
	Tier				TEXT		NOT NULL
	);

-----------------------------------------------
-- CSE_StartBias

-- NOTES:
-- ObjectType can be TERRAIN, FEATURE, RESOURCE or RIVER
-- Object is the latter part of the object, except RIVER which should be NULL
-----------------------------------------------

INSERT INTO CSE_StartBias
		(CityState,				New,	Type,		Object,				Tier	)
VALUES	('AKKAD',				0,		'FEATURE',	'FLOODPLAINS',		2		),
		('AKKAD',				0,		'TERRAIN',	'DESERT',			5		),
		('AKKAD',				0,		'TERRAIN',	'DESERT_HILLS',		5		),
		('AMSTERDAM',			0,		'FEATURE',	'MARSH',			5		),
		('AMSTERDAM',			0,		'TERRAIN',	'COAST',			3		),
		('ANTANANARIVO',		0,		'TERRAIN',	'COAST',			5		),
		('ANTIOCH',				0,		'TERRAIN',	'COAST',			5		),
		('ANTIOCH',				0,		'FEATURE',	'FLOODPLAINS',		3		),
		('ARMAGH',				0,		'TERRAIN',	'GRASS',			5		),
		('ARMAGH',				0,		'TERRAIN',	'GRASS_HILLS',		5		),
		('AUCKLAND',			0,		'TERRAIN',	'COAST',			2		),
		('AUCKLAND',			0,		'TERRAIN',	'GRASS_HILLS',		5		),
		('BABYLON',				0,		'FEATURE',	'FLOODPLAINS',		2		),
		('BABYLON',				0,		'TERRAIN',	'DESERT',			5		),
		('BABYLON',				0,		'TERRAIN',	'DESERT_HILLS',		5		),
		('BOLOGNA',				0,		'TERRAIN',	'GRASS',			5		),
		('BOLOGNA',				0,		'TERRAIN',	'GRASS_HILLS',		5		),
		('BOLOGNA',				0,		'TERRAIN',	'PLAINS',			5		),
		('BOLOGNA',				0,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('BUENOS_AIRES',		0,		'TERRAIN',	'GRASS',			5		),
		('BUENOS_AIRES',		0,		'TERRAIN',	'GRASS_HILLS',		5		),
		('BRUSSELS',			0,		'FEATURE',	'MARSH',			5		),
		('BRUSSELS',			0,		'TERRAIN',	'GRASS',			5		),
		('BRUSSELS',			0,		'TERRAIN',	'GRASS_HILLS',		5		),
		('CAHOKIA',				0,		'TERRAIN',	'PLAINS',			5		),
		('CAHOKIA',				0,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('CARDIFF',				0,		'TERRAIN',	'COAST',			5		),
		('CARDIFF',				0,		'TERRAIN',	'GRASS_HILLS',		5		),
		('CARTHAGE',			0,		'TERRAIN',	'COAST',			5		),
		('CARTHAGE',			0,		'TERRAIN',	'DESERT',			5		),
		('CARTHAGE',			0,		'TERRAIN',	'DESERT_HILLS',		5		),
		('FEZ',					0,		'FEATURE',	'OASIS',			3		),
		('FEZ',					0,		'TERRAIN',	'DESERT',			5		),
		('FEZ',					0,		'TERRAIN',	'DESERT_HILLS',		5		),
		('GENEVA',				0,		'TERRAIN',	'GRASS_MOUNTAIN',	5		),
		('GRANADA',				0,		'TERRAIN',	'PLAINS',			5		),
		('GRANADA',				0,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('HATTUSA',				0,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('HATTUSA',				0,		'TERRAIN',	'DESERT_HILLS',		5		),
		('HONG_KONG',			0,		'TERRAIN',	'COAST',			5		),
		('HONG_KONG',			0,		'TERRAIN',	'GRASS',			5		),
		('HONG_KONG',			0,		'TERRAIN',	'GRASS_HILLS',		5		),
		('JAKARTA',				0,		'TERRAIN',	'COAST',			2		),
		('JAKARTA',				0,		'FEATURE',	'JUNGLE',			2		),
		('JERUSALEM',			0,		'FEATURE',	'FLOODPLAINS',		2		),
		('JERUSALEM',			0,		'TERRAIN',	'DESERT',			5		),
		('JERUSALEM',			0,		'TERRAIN',	'DESERT_HILLS',		5		),
		('KABUL',				0,		'FEATURE',	'FLOODPLAINS',		2		),
		('KABUL',				0,		'TERRAIN',	'DESERT',			5		),
		('KABUL',				0,		'TERRAIN',	'DESERT_HILLS',		5		),
		('KANDY',				0,		'TERRAIN',	'COAST',			5		),
		('KANDY',				0,		'FEATURE',	'JUNGLE',			5		),
		('KUMASI',				0,		'RIVER',	NULL,				5		),
		('LA_VENTA',			0,		'FEATURE',	'JUNGLE',			2		),
		('LISBON',				0,		'TERRAIN',	'COAST',			2		),
		('LISBON',				0,		'TERRAIN',	'PLAINS',			5		),
		('LISBON',				0,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('MEXICO_CITY',			0,		'TERRAIN',	'PLAINS',			5		),
		('MEXICO_CITY',			0,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('MOHENJO_DARO',		0,		'RIVER',	NULL,				5		),
		('MOHENJO_DARO',		0,		'TERRAIN',	'COAST',			3		),
		('MOHENJO_DARO',		0,		'FEATURE',	'JUNGLE',			5		),
		('MUSCAT',				0,		'FEATURE',	'OASIS',			3		),
		('MUSCAT',				0,		'TERRAIN',	'DESERT',			5		),
		('MUSCAT',				0,		'TERRAIN',	'DESERT_HILLS',		5		),
		('NAN_MADOL',			0,		'TERRAIN',	'COAST',			2		),
		('NAN_MADOL',			0,		'FEATURE',	'JUNGLE',			2		),
		('NAZCA',				0,		'TERRAIN',	'DESERT',			3		),
		('NAZCA',				0,		'TERRAIN',	'DESERT_HILLS',		3		),
		('NGAZARGAMU',			0,		'FEATURE',	'JUNGLE',			3		),
		('PALENQUE',			0,		'FEATURE',	'JUNGLE',			3		),
		('PRESLAV',				0,		'TERRAIN',	'GRASS_HILLS',		5		),
		('RAPA_NUI',			0,		'TERRAIN',	'COAST',			2		),
		('RAPA_NUI',			0,		'FEATURE',	'JUNGLE',			3		),
		('RAPA_NUI',			0,		'FEATURE',	'VOLCANO',			3		),
		('SEOUL',				0,		'FEATURE',	'FOREST',			5		),
		('STOCKHOLM',			0,		'TERRAIN',	'TUNDRA',			5		),
		('STOCKHOLM',			0,		'TERRAIN',	'TUNDRA_HILLS',		5		),
		('VILNIUS',				0,		'TERRAIN',	'GRASS',			5		),
		('VILNIUS',				0,		'TERRAIN',	'GRASS_HILLS',		5		),
		('YEREVAN',				0,		'TERRAIN',	'GRASS_MOUNTAIN',	5		),
		('YEREVAN',				0,		'TERRAIN',	'PLAINS_MOUNTAIN',	5		),
		('ZANZIBAR',			0,		'FEATURE',	'JUNGLE',			3		),
		
		-- CSE
		('CSE_ALAMUT',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_ALAMUT',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_ALAMUT',			1,		'TERRAIN',	'DESERT_MOUNTAIN',	3		),
		('CSE_AMPI',			1,		'TERRAIN',	'COAST',			2		),
		('CSE_AMPI',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_AMPI',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_AYNUK',			1,		'TERRAIN',	'COAST',			2		),
		('CSE_AYNUK',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_AYNUK',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_AZCAPOTZALCO',	1,		'FEATURE',	'JUNGLE',			3		),
		('CSE_BAIAE',			1,		'TERRAIN',	'GRASS',			5		),
		('CSE_BAIAE',			1,		'TERRAIN',	'GRASS_HILLS',		5		),
		('CSE_BAIAE',			1,		'TERRAIN',	'COAST',			5		),
		('CSE_BEIKTHANO',		1,		'FEATURE',	'JUNGLE',			3		),
		('CSE_BUTUAN',			1,		'TERRAIN',	'COAST',			2		),
		('CSE_BUTUAN',			1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_CATALHOYUK',		1,		'TERRAIN',	'PLAINS',			5		),
		('CSE_CATALHOYUK',		1,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('CSE_CHAN_CHAN',		1,		'TERRAIN',	'DESERT',			5		),
		('CSE_CHAN_CHAN',		1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_CHETRO_KETL',		1,		'TERRAIN',	'DESERT',			5		),
		('CSE_CHETRO_KETL',		1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_DAKAR',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_DAKAR',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_DAKAR',			1,		'TERRAIN',	'COAST',			1		),
		('CSE_DELOS',			1,		'TERRAIN',	'COAST',			5		),
		('CSE_DELOS',			1,		'TERRAIN',	'GRASS',			5		),
		('CSE_DELOS',			1,		'TERRAIN',	'GRASS_HILLS',		5		),
		('CSE_DELPHI',			1,		'TERRAIN',	'COAST',			5		),
		('CSE_DELPHI',			1,		'TERRAIN',	'GRASS',			5		),
		('CSE_DELPHI',			1,		'TERRAIN',	'GRASS_HILLS',		5		),
		('CSE_DJIBOUTI',		1,		'TERRAIN',	'DESERT',			5		),
		('CSE_DJIBOUTI',		1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_DJIBOUTI',		1,		'TERRAIN',	'COAST',			1		),
		('CSE_DODONA',			1,		'TERRAIN',	'COAST',			5		),
		('CSE_ETZANOA',			1,		'TERRAIN',	'PLAINS',			5		),
		('CSE_ETZANOA',			1,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('CSE_GARAMA',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_GARAMA',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_GOBEKLI_TEPE',	1,		'TERRAIN',	'PLAINS',			5		),
		('CSE_GOBEKLI_TEPE',	1,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('CSE_GUNDESHAPUR',		1,		'TERRAIN',	'DESERT',			5		),
		('CSE_GUNDESHAPUR',		1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_HADAD',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_HADAD',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_HALIN',			1,		'FEATURE',	'FOREST',			5		),
		('CSE_HAVANA',			1,		'TERRAIN',	'COAST',			1		),
		('CSE_HAVANA',			1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_HAZOR',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_HAZOR',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_HORMUZ',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_HORMUZ',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_HORMUZ',			1,		'TERRAIN',	'COAST',			1		),
		('CSE_HVALSEY',			1,		'TERRAIN',	'COAST',			2		),
		('CSE_HVALSEY',			1,		'TERRAIN',	'TUNDRA',			3		),
		('CSE_HVALSEY',			1,		'TERRAIN',	'TUNDRA_HILLS',		3		),
		('CSE_HVALSEY',			1,		'TERRAIN',	'SNOW',				3		),
		('CSE_HVALSEY',			1,		'TERRAIN',	'SNOW_HILLS',		3		),
		('CSE_HVALSEY',			1,		'FEATURE',	'ICE',				3		),
		('CSE_IQALUIT',			1,		'TERRAIN',	'COAST',			2		),
		('CSE_IQALUIT',			1,		'TERRAIN',	'TUNDRA',			3		),
		('CSE_IQALUIT',			1,		'TERRAIN',	'TUNDRA_HILLS',		3		),
		('CSE_IQALUIT',			1,		'TERRAIN',	'SNOW',				3		),
		('CSE_IQALUIT',			1,		'TERRAIN',	'SNOW_HILLS',		3		),
		('CSE_IQALUIT',			1,		'FEATURE',	'ICE',				3		),
		('CSE_IZAPA',			1,		'FEATURE',	'JUNGLE',			3		),
		('CSE_JOHANNESBURG',	1,		'FEATURE',	'FOREST',			5		),
		('CSE_JOLO',			1,		'FEATURE',	'JUNGLE',			3		),
		('CSE_KADESH',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_KADESH',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_KANNAUJ',			1,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('CSE_KATARAGAMA',		1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_KELANIYA',		1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_KUHIKUGU',		1,		'FEATURE',	'JUNGLE',			3		),
		('CSE_LIMA',			1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_LIMA',			1,		'TERRAIN',	'PLAINS',			5		),
		('CSE_LIMA',			1,		'TERRAIN',	'PLAINS_HILLS',		5		),
		('CSE_MACAU',			1,		'TERRAIN',	'COAST',			3		),
		('CSE_MACAU',			1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_MAI',				1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_MAINGMAW',		1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_MARRAKECH',		1,		'FEATURE',	'FLOODPLAINS',		3		),
		('CSE_MARRAKECH',		1,		'TERRAIN',	'DESERT',			5		),
		('CSE_MARRAKECH',		1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_MEGIDDO',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_MEHRGARH',		1,		'TERRAIN',	'DESERT',			5		),
		('CSE_MOMBASA',			1,		'TERRAIN',	'COAST',			1		),
		('CSE_MOMBASA',			1,		'FEATURE',	'JUNGLE',			3		),
		('CSE_MONACO',			1,		'TERRAIN',	'COAST',			3		),
		('CSE_MZIZIMA',			1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_NALANDA',			1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_NASSAU',			1,		'TERRAIN',	'COAST',			1		),
		('CSE_NASSAU',			1,		'TERRAIN',	'DESERT',			3		),
		('CSE_NASSAU',			1,		'TERRAIN',	'DESERT_HILLS',		3		),
		('CSE_NASSAU',			1,		'FEATURE',	'JUNGLE',			3		),
		('CSE_PALMYRA',			1,		'FEATURE',	'OASIS',			3		),
		('CSE_PALMYRA',			1,		'FEATURE',	'FLOODPLAINS',		5		),
		('CSE_PALMYRA',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_PALMYRA',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_PHASIS',			1,		'FEATURE',	'FOREST',			5		),
		('CSE_PORT_ROYAL',		1,		'TERRAIN',	'COAST',			2		),
		('CSE_SALE',			1,		'TERRAIN',	'COAST',			2		),
		('CSE_SALE',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_SALE',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_SAMARQAND',		1,		'TERRAIN',	'DESERT',			5		),
		('CSE_SAMARQAND',		1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_SANAA',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_SANAA',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_SHAHR_E_SUKHTE',	1,		'TERRAIN',	'DESERT',			5		),
		('CSE_SHAHR_E_SUKHTE',	1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_SIDON',			1,		'TERRAIN',	'COAST',			3		),
		('CSE_SINGAPORE',		1,		'TERRAIN',	'COAST',			3		),
		('CSE_SRI_KSETRA',		1,		'FEATURE',	'JUNGLE',			5		),
		('CSE_TANGIER',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_TANGIER',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_TAOS',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_TAOS',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_TUNERIUT',		1,		'TERRAIN',	'COAST',			2		),
		('CSE_TUNERIUT',		1,		'TERRAIN',	'TUNDRA',			3		),
		('CSE_TUNERIUT',		1,		'TERRAIN',	'TUNDRA_HILLS',		3		),
		('CSE_UGARIT',			1,		'TERRAIN',	'COAST',			2		),
		('CSE_URGENCH',			1,		'TERRAIN',	'DESERT',			5		),
		('CSE_URGENCH',			1,		'TERRAIN',	'DESERT_HILLS',		5		),
		('CSE_VADUZ',			1,		'TERRAIN',	'GRASS_MOUNTAIN',	5		),
		('CSE_VALABHI',			1,		'FEATURE',	'JUNGLE',			3		),
		('CSE_VIENNA',			1,		'TERRAIN',	'GRASS_HILLS',		5		),
		('CSE_WYAM',			1,		'TERRAIN',	'COAST',			3		);