/*
	Master
	Authors: thecrazyscotsman, Chrisy15, ChimpanG
*/

-----------------------------------------------
-- Schema
-----------------------------------------------

CREATE TABLE IF NOT EXISTS CSE_ClassTypes
	(
	Type				TEXT	NOT NULL, 
	LeaderType			TEXT	DEFAULT NULL, 
	TypeName			TEXT	DEFAULT NULL, 
	SmallBonus			TEXT	DEFAULT NULL, 
	MediumBonus			TEXT	DEFAULT NULL, 
	LargeBonus			TEXT	DEFAULT NULL, 
	LargestBonus		TEXT	DEFAULT NULL,
	TraitType			TEXT	DEFAULT NULL,
	TraitDescription	TEXT	DEFAULT NULL,
	MinorCivBonus		TEXT	DEFAULT NULL,
	BonusIcon			TEXT	DEFAULT NULL, 
	TypeIcon			TEXT	DEFAULT NULL, 
	Color				TEXT	DEFAULT NULL,
	ColorRef			TEXT	DEFAULT NULL,
	New					INTEGER	DEFAULT 1
	);

CREATE TABLE IF NOT EXISTS CSE_Master
	(
	CityState			TEXT		NOT NULL,
	CivilizationType	TEXT		DEFAULT NULL,
	LeaderType			TEXT		DEFAULT NULL,
	New					BOOLEAN		DEFAULT 0,
	CityStateType		TEXT		DEFAULT NULL, 
	CityStateLeaderType	TEXT		DEFAULT NULL,
	ProposedType		TEXT		NOT NULL,
	FallbackType		TEXT		DEFAULT NULL,
	UseFallback			BOOLEAN		DEFAULT 0,
	MinorCivBonus		TEXT		DEFAULT NULL,
	Ethnicity			TEXT		DEFAULT NULL,
	Requires			TEXT		DEFAULT NULL,
	Version				TEXT		DEFAULT NULL,
	Removed				TEXT		DEFAULT NULL,
	Discard				BOOLEAN		DEFAULT 0,
	ColorRef			TEXT		DEFAULT NULL,

	PRIMARY KEY (CityState)
	);

-----------------------------------------------
-- CSE_ClassTypes
-----------------------------------------------

INSERT INTO CSE_ClassTypes
		(Type,					New,	Color,				BonusIcon,								TypeIcon,							TraitType,								TraitDescription							)
VALUES	('SCIENTIFIC',			0,		'50,202,237,255',	'ICON_ENVOY_BONUS_SCIENCE',				'ICON_CITYSTATE_SCIENCE',			'MINOR_CIV_SCIENTIFIC_TRAIT',			'LOC_CSE_SCIENTIFIC_TRAIT_DESCRIPTION'		),
		('RELIGIOUS',			0,		'255,246,235,255',	'ICON_ENVOY_BONUS_FAITH',				'ICON_CITYSTATE_FAITH',				'MINOR_CIV_RELIGIOUS_TRAIT',			'LOC_CSE_RELIGIOUS_TRAIT_DESCRIPTION'		),
		('TRADE',				0,		'255,206,108,255',	'ICON_ENVOY_BONUS_GOLD',				'ICON_CITYSTATE_TRADE',				'MINOR_CIV_TRADE_TRAIT',				'LOC_CSE_TRADE_TRAIT_DESCRIPTION'			),
		('CULTURAL',			0,		'214,102,255,255',	'ICON_ENVOY_BONUS_CULTURE',				'ICON_CITYSTATE_CULTURE',			'MINOR_CIV_CULTURAL_TRAIT',				'LOC_CSE_CULTURAL_TRAIT_DESCRIPTION'		),
		('MILITARISTIC',		0,		'255,92,92,255',	'ICON_ENVOY_BONUS_MILITARISTIC',		'ICON_CITYSTATE_MILITARISTIC',		'MINOR_CIV_MILITARISTIC_TRAIT',			'LOC_CSE_MILITARISTIC_TRAIT_DESCRIPTION'	),
		('INDUSTRIAL',			0,		'255,149,77,255',	'ICON_ENVOY_BONUS_INDUSTRIAL',			'ICON_CITYSTATE_INDUSTRIAL',		'MINOR_CIV_INDUSTRIAL_TRAIT',			'LOC_CSE_INDUSTRIAL_TRAIT_DESCRIPTION'		),
		('CSE_AGRICULTURAL',	1,		'159,226,100,255',	'ICON_ENVOY_BONUS_CSE_AGRICULTURAL',	'ICON_CITYSTATE_CSE_AGRICULTURAL',	'MINOR_CIV_CSE_AGRICULTURAL_TRAIT',		'LOC_CSE_AGRICULTURAL_TRAIT_DESCRIPTION'	),
		('CSE_CONSULAR',		1,		'144,128,255,255',	'ICON_ENVOY_BONUS_CSE_CONSULAR',		'ICON_CITYSTATE_CSE_CONSULAR',		'MINOR_CIV_CSE_CONSULAR_TRAIT',			'LOC_CSE_CONSULAR_TRAIT_DESCRIPTION'		),
		('CSE_ENTERTAINMENT',	1,		'255,100,170,255',	'ICON_ENVOY_BONUS_CSE_ENTERTAINMENT',	'ICON_CITYSTATE_CSE_ENTERTAINMENT',	'MINOR_CIV_CSE_ENTERTAINMENT_TRAIT',	'LOC_CSE_ENTERTAINMENT_TRAIT_DESCRIPTION'	),
		('CSE_MARITIME',		1,		'88,220,195,255',	'ICON_ENVOY_BONUS_CSE_MARITIME',		'ICON_CITYSTATE_CSE_MARITIME',		'MINOR_CIV_CSE_MARITIME_TRAIT',			'LOC_CSE_MARITIME_TRAIT_DESCRIPTION'		);

-----------------------------------------------
-- CSE_Master
-----------------------------------------------

INSERT INTO CSE_Master
		(CityState,				New,	ProposedType,			FallbackType,			Ethnicity,				Requires,	Version,				Removed				)
VALUES	('AKKAD',				0,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('AMSTERDAM',			0,		'TRADE',				NULL,					'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	'XP1'				),
		('ANTANANARIVO',		0,		'CULTURAL',				NULL,					'ETHNICITY_MEDIT',		'DLC2',		'CITY_STATES_EXPANDED',	NULL				),
		('ANTIOCH',				0,		'TRADE',				NULL,					'ETHNICITY_MEDIT',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('ARMAGH',				0,		'RELIGIOUS',			NULL,					'ETHNICITY_EURO',		'DLC2',		'CITY_STATES_EXPANDED',	NULL				),
		('AUCKLAND',			0,		'INDUSTRIAL',			NULL,					'ETHNICITY_EURO',		'DLC2',		'CITY_STATES_EXPANDED',	NULL				),
		('BABYLON',				0,		'SCIENTIFIC',			NULL,					'ETHNICITY_EURO',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('BOLOGNA',				0,		'SCIENTIFIC',			NULL,					'ETHNICITY_EURO',		'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('BUENOS_AIRES',		0,		'CSE_AGRICULTURAL',		'INDUSTRIAL',			'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('BRUSSELS',			0,		'CSE_CONSULAR',			'INDUSTRIAL',			'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CAHOKIA',				0,		'CSE_AGRICULTURAL',		'TRADE',				'ETHNICITY_SOUTHAM',	'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('CARDIFF',				0,		'INDUSTRIAL',			NULL,					'ETHNICITY_EURO',		'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('CARTHAGE',			0,		'MILITARISTIC',			NULL,					'ETHNICITY_AFRICAN',	'BASE',		'CITY_STATES_EXPANDED',	'XP2'				),
		('FEZ',					0,		'SCIENTIFIC',			NULL,					'ETHNICITY_AFRICAN',	'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('GENEVA',				0,		'CSE_CONSULAR',			'SCIENTIFIC',			'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('GRANADA',				0,		'MILITARISTIC',			NULL,					'ETHNICITY_EURO',		'DLC2',		'CITY_STATES_EXPANDED',	NULL				),
		('HATTUSA',				0,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('HONG_KONG',			0,		'INDUSTRIAL',			NULL,					'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('JAKARTA',				0,		'CSE_MARITIME',			'TRADE',				'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('JERUSALEM',			0,		'RELIGIOUS',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('KABUL',				0,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('KANDY',				0,		'RELIGIOUS',			NULL,					'ETHNICITY_AFRICAN',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('KUMASI',				0,		'CULTURAL',				NULL,					'ETHNICITY_AFRICAN',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('LA_VENTA',			0,		'RELIGIOUS',			NULL,					'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('LISBON',				0,		'CSE_MARITIME',			'TRADE',				'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('MEXICO_CITY',			0,		'INDUSTRIAL',			NULL,					'ETHNICITY_SOUTHAM',	'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('MOHENJO_DARO',		0,		'CULTURAL',				NULL,					'ETHNICITY_AFRICAN',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('MUSCAT',				0,		'TRADE',				NULL,					'ETHNICITY_AFRICAN',	'DLC2',		'CITY_STATES_EXPANDED',	NULL				),
		('NAN_MADOL',			0,		'CULTURAL',				NULL,					'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('NAZCA',				0,		'RELIGIOUS',			NULL,					'ETHNICITY_SOUTHAM',	'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('NGAZARGAMU',			0,		'MILITARISTIC',			NULL,					'ETHNICITY_AFRICAN',	'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('PALENQUE',			0,		'SCIENTIFIC',			NULL,					'ETHNICITY_SOUTHAM',	'DLC2',		'CITY_STATES_EXPANDED',	'NF1'				),
		('PRESLAV',				0,		'MILITARISTIC',			NULL,					'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('RAPA_NUI',			0,		'CULTURAL',				NULL,					'ETHNICITY_SOUTHAM',	'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('SEOUL',				0,		'SCIENTIFIC',			NULL,					'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	'XP1'				),
		('STOCKHOLM',			0,		'SCIENTIFIC',			NULL,					'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	'XP2'				),
		('TORONTO',				0,		'INDUSTRIAL',			NULL,					'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	'XP2'				),
		('VALLETTA',			0,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('VILNIUS',				0,		'CULTURAL',				NULL,					'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('YEREVAN',				0,		'RELIGIOUS',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('ZANZIBAR',			0,		'TRADE',				NULL,					'ETHNICITY_AFRICAN',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),

		('CAGUANA',				0,		'CULTURAL',				NULL,					'ETHNICITY_SOUTHAM',	'NF1',		'CITY_STATES_EXPANDED',	NULL				),
		('HUNZA',				0,		'TRADE',				NULL,					'ETHNICITY_SOUTHAM',	'NF1',		'CITY_STATES_EXPANDED',	NULL				),
		('LAHORE',				0,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'NF1',		'CITY_STATES_EXPANDED',	NULL				),
		('SINGAPORE',			0,		'INDUSTRIAL',			NULL,					'ETHNICITY_ASIAN',		'NF1',		'CITY_STATES_EXPANDED',	NULL				),
		('TARUGA',				0,		'SCIENTIFIC',			NULL,					'ETHNICITY_AFRICAN',	'NF1',		'CITY_STATES_EXPANDED',	NULL				),
		('VATICAN_CITY',		0,		'RELIGIOUS',			NULL,					'ETHNICITY_MEDIT',		'NF1',		'CITY_STATES_EXPANDED',	NULL				),

		-- CSE
		('CSE_ALAMUT',			1,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_AMPI',			1,		'CSE_MARITIME',			'TRADE',				'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_ANURADHAPURA',	1,		'SCIENTIFIC',			NULL,					'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_AYNUK',			1,		'CSE_MARITIME',			'INDUSTRIAL',			'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_AZCAPOTZALCO',	1,		'CSE_CONSULAR',			'MILITARISTIC',			'ETHNICITY_SOUTHAM',	'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_BAIAE',			1,		'CSE_ENTERTAINMENT',	'CULTURAL',				'ETHNICITY_MEDIT',		'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_BEIKTHANO',		1,		'MILITARISTIC',			NULL,					'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_BUTUAN',			1,		'CSE_MARITIME',			'CULTURAL',				'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_CATALHOYUK',		1,		'CSE_AGRICULTURAL',		'TRADE',				'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_CHAN_CHAN',		1,		'CSE_ENTERTAINMENT',	'CULTURAL',				'ETHNICITY_SOUTHAM',	'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_CHETRO_KETL',		1,		'CSE_CONSULAR',			'RELIGIOUS',			'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_DAKAR',			1,		'CSE_MARITIME',			'TRADE',				'ETHNICITY_AFRICAN',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_DELOS',			1,		'CSE_ENTERTAINMENT',	'CULTURAL',				'ETHNICITY_MEDIT',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_DELPHI',			1,		'CSE_CONSULAR',			'CULTURAL',				'ETHNICITY_MEDIT',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_DJIBOUTI',		1,		'CSE_MARITIME',			'TRADE',				'ETHNICITY_AFRICAN',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_DODONA',			1,		'CULTURAL',				NULL,					'ETHNICITY_MEDIT',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_ETZANOA',			1,		'CSE_AGRICULTURAL',		'CULTURAL',				'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_GARAMA',			1,		'TRADE',				NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_GOBEKLI_TEPE',	1,		'CULTURAL',				NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_GUNDESHAPUR',		1,		'CSE_CONSULAR',			'SCIENTIFIC',			'ETHNICITY_MEDIT',		'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_HADAD',			1,		'CSE_CONSULAR',			'CULTURAL',				'ETHNICITY_MEDIT',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_HALIN',			1,		'RELIGIOUS',			NULL,					'ETHNICITY_ASIAN',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_HAVANA',			1,		'CSE_MARITIME',			'CULTURAL',				'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_HAZOR',			1,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_HORMUZ',			1,		'CSE_MARITIME',			'TRADE',				'ETHNICITY_MEDIT',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_HVALSEY',			1,		'CSE_AGRICULTURAL',		'INDUSTRIAL',			'ETHNICITY_EURO',		'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_IQALUIT',			1,		'CSE_AGRICULTURAL',		'CULTURAL',				'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_IZAPA',			1,		'SCIENTIFIC',			NULL,					'ETHNICITY_SOUTHAM',	'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_JOHANNESBURG',	1,		'INDUSTRIAL',			NULL,					'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_JOLO',			1,		'CSE_AGRICULTURAL',		'TRADE',				'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_KADESH',			1,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_KANNAUJ',			1,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_KATARAGAMA',		1,		'RELIGIOUS',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_KELANIYA',		1,		'CULTURAL',				NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_KUHIKUGU',		1,		'CSE_AGRICULTURAL',		'INDUSTRIAL',			'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_LIMA',			1,		'SCIENTIFIC',			NULL,					'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_MACAU',			1,		'CSE_ENTERTAINMENT',	'TRADE',				'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_MAI',				1,		'TRADE',				NULL,					'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_MAINGMAW',		1,		'CSE_AGRICULTURAL',		'CULTURAL',				'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_MEGIDDO',			1,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_MEHRGARH',		1,		'CSE_AGRICULTURAL',		'INDUSTRIAL',			'ETHNICITY_MEDIT',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_MOMBASA',			1,		'CSE_MARITIME',			'TRADE',				'ETHNICITY_AFRICAN',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_MONACO',			1,		'CSE_ENTERTAINMENT',	'CULTURAL',				'ETHNICITY_EURO',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_MZIZIMA',			1,		'CSE_CONSULAR',			'INDUSTRIAL',			'ETHNICITY_AFRICAN',	'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_NALANDA',			1,		'SCIENTIFIC',			NULL,					'ETHNICITY_MEDIT',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_NASSAU',			1,		'CSE_MARITIME',			'TRADE',				'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_PALMYRA',			1,		'TRADE',				NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_PHASIS',			1,		'INDUSTRIAL',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_PORT_ROYAL',		1,		'CSE_MARITIME',			'TRADE',				'ETHNICITY_EURO',		'XP1',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_QATNA',			1,		'INDUSTRIAL',			NULL,					'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_SALE',			1,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_SAMARQAND',		1,		'SCIENTIFIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_SANAA',			1,		'CSE_AGRICULTURAL',		'TRADE',				'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_SEUTHOPOLIS',		1,		'MILITARISTIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_SHAHR_E_SUKHTE',	1,		'CULTURAL',				NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_SIDON',			1,		'CSE_ENTERTAINMENT',	'MILITARISTIC',			'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_SINGAPORE',		1,		'TRADE',				NULL,					'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_SRI_KSETRA',		1,		'CSE_AGRICULTURAL',		'RELIGIOUS',			'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_TANGIER',			1,		'CSE_CONSULAR',			'CULTURAL',				'ETHNICITY_MEDIT',		'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_TAOS',			1,		'SCIENTIFIC',			NULL,					'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_TEYUNA',			1,		'INDUSTRIAL',			NULL,					'ETHNICITY_SOUTHAM',	'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_TISSAMAHARAMA',	1,		'MILITARISTIC',			NULL,					'ETHNICITY_ASIAN',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_TUNERIUT',		1,		'TRADE',				NULL,					'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_UGARIT',			1,		'CSE_MARITIME',			'INDUSTRIAL',			'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_URGENCH',			1,		'TRADE',				NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_VADUZ',			1,		'CSE_CONSULAR',			'TRADE',				'ETHNICITY_EURO',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_VALABHI',			1,		'SCIENTIFIC',			NULL,					'ETHNICITY_MEDIT',		'BASE',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_VIENNA',			1,		'CSE_CONSULAR',			'CULTURAL',				'ETHNICITY_EURO',		'XP2',		'CITY_STATES_EXPANDED',	NULL				),
		('CSE_WYAM',			1,		'CULTURAL',				NULL,					'ETHNICITY_SOUTHAM',	'BASE',		'CITY_STATES_EXPANDED',	NULL				);

