--=====
--TYPES
--=====
INSERT INTO Types
				(Type, 									Kind)
VALUES	('CVS_RESOURCE_ABACA', 	'KIND_RESOURCE'),
				('CVS_RESOURCE_GLASS', 	'KIND_RESOURCE'),
				('CVS_RESOURCE_LEATHER', 	'KIND_RESOURCE'),
				('CVS_RESOURCE_MANGOSTEEN', 	'KIND_RESOURCE'),
				('CVS_RESOURCE_SERIC_IRON', 	'KIND_RESOURCE'),
				('CVS_RESOURCE_WALRUS', 	'KIND_RESOURCE');

--=========
--RESOURCES
--=========
INSERT INTO Resources
				(ResourceType, 							Name, 															ResourceClassType, 						Happiness, Frequency)
VALUES	('CVS_RESOURCE_ABACA', 			'LOC_CVS_RESOURCE_ABACA_NAME', 			'RESOURCECLASS_LUXURY', 			6, 			0),
				('CVS_RESOURCE_GLASS', 			'LOC_CVS_RESOURCE_GLASS_NAME', 			'RESOURCECLASS_LUXURY', 			4, 			0),
				('CVS_RESOURCE_LEATHER',			'LOC_CVS_RESOURCE_LEATHER_NAME', 		'RESOURCECLASS_LUXURY', 			6, 			0),
				('CVS_RESOURCE_MANGOSTEEN',	'LOC_CVS_RESOURCE_MANGOSTEEN_NAME', 	'RESOURCECLASS_LUXURY', 			6, 			0),
				('CVS_RESOURCE_SERIC_IRON', 	'LOC_CVS_RESOURCE_SERIC_IRON_NAME', 	'RESOURCECLASS_STRATEGIC', 	0, 			0),
				('CVS_RESOURCE_WALRUS', 			'LOC_CVS_RESOURCE_WALRUS_NAME', 			'RESOURCECLASS_LUXURY', 			4, 			0);