--=======
--AI STUFF
--=======
--City-States build more districts
DELETE FROM AiFavoredItems
WHERE ListType = 'MinorCivDistricts' AND Item = 'DISTRICT_COMMERCIAL_HUB';

DELETE FROM AiFavoredItems
WHERE ListType = 'MinorCivDistricts' AND Item = 'DISTRICT_ENTERTAINMENT_COMPLEX';

DELETE FROM AiFavoredItems
WHERE ListType = 'MinorCivDistricts' AND Item = 'DISTRICT_WATER_ENTERTAINMENT_COMPLEX';

DELETE FROM AiFavoredItems
WHERE ListType = 'MinorCivDistricts' AND Item = 'DISTRICT_AQUEDUCT';

DELETE FROM AiFavoredItems
WHERE ListType = 'MinorCivDistricts' AND Item = 'DISTRICT_CAMPUS';

DELETE FROM AiFavoredItems
WHERE ListType = 'MinorCivDistricts' AND Item = 'DISTRICT_THEATER';

--City-States don't build recon
DELETE FROM AiFavoredItems
WHERE ListType = 'MinorCivUnitBuilds' AND Item = 'PROMOTION_CLASS_RECON';

INSERT INTO AiFavoredItems (ListType, Item, Favored)
	VALUES
		('MinorCivUnitBuilds', 'PROMOTION_CLASS_RECON', 0);

--=============
--CIVILIZATIONS/TRAITS
--=============
UPDATE CivilizationLevels
SET CanAnnexTilesWithGold = 1, StartingTilesForCity = 6
WHERE CivilizationLevelType = 'CIVILIZATION_LEVEL_CITY_STATE';

UPDATE Traits
SET Description = 'LOC_CVS_CITYSTATES_LEADER_TRAIT_MUSCAT_DESCRIPTION'
WHERE TraitType = 'MINOR_CIV_MUSCAT_TRAIT'
AND EXISTS (SELECT * FROM Traits WHERE TraitType = 'MINOR_CIV_MUSCAT_TRAIT');

--============
--TYPE PROPERTIES
--============
--AGRICULTURAL
UPDATE TypeProperties
SET Value = 'CVS_AGRICULTURAL'
WHERE Type = 'CIVILIZATION_MOHENJO_DARO'
OR Type = 'CIVILIZATION_BUENOS_AIRES';

UPDATE Leaders
SET InheritFrom = 'CVS_LEADER_MINOR_CIV_AGRICULTURAL'
WHERE LeaderType = 'LEADER_MINOR_CIV_MOHENJO_DARO'
OR LeaderType = 'LEADER_MINOR_CIV_BUENOS_AIRES';

UPDATE PlayerColors
SET SecondaryColor = 'COLOR_PLAYER_CITY_STATE_CVS_AGRICULTURAL_SECONDARY', TextColor = 'COLOR_PLAYER_CITY_STATE_CVS_AGRICULTURAL_SECONDARY'
WHERE Type = 'CIVILIZATION_MOHENJO_DARO'
OR Type = 'CIVILIZATION_BUENOS_AIRES';

--CONSULAR
UPDATE TypeProperties
SET Value = 'CVS_CONSULAR'
WHERE Type = 'CIVILIZATION_BRUSSELS'
OR Type = 'CIVILIZATION_GENEVA';

UPDATE Leaders
SET InheritFrom = 'CVS_LEADER_MINOR_CIV_CONSULAR'
WHERE LeaderType = 'LEADER_MINOR_CIV_BRUSSELS'
OR LeaderType = 'LEADER_MINOR_CIV_GENEVA';

UPDATE PlayerColors
SET SecondaryColor = 'COLOR_PLAYER_CITY_STATE_CVS_CONSULAR_SECONDARY', TextColor = 'COLOR_PLAYER_CITY_STATE_CVS_CONSULAR_SECONDARY'
WHERE Type = 'CIVILIZATION_BRUSSELS'
OR Type = 'CIVILIZATION_GENEVA';

--ENTERTAINMENT
UPDATE TypeProperties
SET Value = 'CVS_ENTERTAINMENT'
WHERE Type = 'CIVILIZATION_PALENQUE'
AND EXISTS (SELECT * FROM TypeProperties WHERE Type = 'CIVILIZATION_PALENQUE');

UPDATE Leaders
SET InheritFrom = 'CVS_LEADER_MINOR_CIV_ENTERTAINMENT'
WHERE LeaderType = 'LEADER_MINOR_CIV_PALENQUE'
AND EXISTS (SELECT * FROM Leaders WHERE LeaderType = 'LEADER_MINOR_CIV_PALENQUE');

UPDATE PlayerColors
SET SecondaryColor = 'COLOR_PLAYER_CITY_STATE_CVS_ENTERTAINMENT_SECONDARY', TextColor = 'COLOR_PLAYER_CITY_STATE_CVS_ENTERTAINMENT_SECONDARY'
WHERE Type = 'CIVILIZATION_PALENQUE'
AND EXISTS (SELECT * FROM PlayerColors WHERE Type = 'CIVILIZATION_PALENQUE');

--MARITIME
UPDATE TypeProperties
SET Value = 'CVS_MARITIME'
WHERE Type = 'CIVILIZATION_LISBON'
OR Type = 'CIVILIZATION_CARTHAGE';

UPDATE Leaders
SET InheritFrom = 'CVS_LEADER_MINOR_CIV_MARITIME'
WHERE LeaderType = 'LEADER_MINOR_CIV_LISBON'
OR LeaderType = 'LEADER_MINOR_CIV_CARTHAGE';

UPDATE PlayerColors
SET SecondaryColor = 'COLOR_PLAYER_CITY_STATE_CVS_MARITIME_SECONDARY', TextColor = 'COLOR_PLAYER_CITY_STATE_CVS_MARITIME_SECONDARY'
WHERE Type = 'CIVILIZATION_LISBON'
OR Type = 'CIVILIZATION_CARTHAGE';

--=====
--TYPES
--=====
INSERT INTO Types 
				(Type, 																		Kind)
VALUES	('CVS_MINOR_CIV_GRANT_WALLS_IN_CITY_IGNORE', 'KIND_MODIFIER'),
		('CVS_MODIFIER_MUSCAT_PLAYER_CITIES_ADJUST_AMENITIES_FROM_CITY_STATES', 'KIND_MODIFIER');

--=================
--DYNAMIC MODIFIERS
--=================		
INSERT INTO DynamicModifiers 
				(ModifierType, 															CollectionType, 							EffectType)
VALUES	('CVS_MINOR_CIV_GRANT_WALLS_IN_CITY_IGNORE', 'COLLECTION_PLAYER_CITIES', 	'EFFECT_GRANT_BUILDING_IN_CITY_IGNORE'),
		('CVS_MODIFIER_MUSCAT_PLAYER_CITIES_ADJUST_AMENITIES_FROM_CITY_STATES',		'COLLECTION_PLAYER_CITIES',	'EFFECT_ADJUST_CITY_AMENITIES_FROM_CITY_STATES');
	
--===============
--TRAIT MODIFIERS
--===============
INSERT INTO TraitModifiers 
				(TraitType, 										ModifierId)
VALUES	--Free walls
				('MINOR_CIV_DEFAULT_TRAIT', 			'CVS_MINOR_CIV_FREE_ANCIENT_WALLS'),
				--('MINOR_CIV_DEFAULT_TRAIT', 			'CVS_MINOR_CIV_FREE_MEDIEVAL_WALLS'),
				--('MINOR_CIV_DEFAULT_TRAIT', 			'CVS_MINOR_CIV_FREE_RENAISSANCE_WALLS'),
				--City-states benefit from traits
				('MINOR_CIV_ANTIOCH_TRAIT', 		'MINOR_CIV_ANTIOCH_LUXURY_TRADE_ROUTE_BONUS'),
				('MINOR_CIV_BUENOS_AIRES_TRAIT', 'MINOR_CIV_BUENOS_AIRES_BONUS_RESOURCE_AMENITY_BONUS'),
				('MINOR_CIV_CARTHAGE_TRAIT', 		'MINOR_CIV_CARTHAGE_BARRACKS_STABLE_PURCHASE_BONUS'),
				('MINOR_CIV_CARTHAGE_TRAIT', 		'MINOR_CIV_CARTHAGE_ARMORY_PURCHASE_BONUS'),
				('MINOR_CIV_CARTHAGE_TRAIT', 		'MINOR_CIV_CARTHAGE_MILITARY_ACADEMY_PURCHASE_BONUS'),
				('MINOR_CIV_GENEVA_TRAIT', 			'MINOR_CIV_GENEVA_SCIENCE_AT_PEACE_BONUS'),
				('MINOR_CIV_HONG_KONG_TRAIT',	'MINOR_CIV_HONG_KONG_PROJECT_PRODUCTION_BONUS'),
				('MINOR_CIV_JAKARTA_TRAIT', 			'MINOR_CIV_JAKARTA_TRADING_POST_BONUS'),
				('MINOR_CIV_JERUSALEM_TRAIT', 		'MINOR_CIV_JERUSALEM_HOLY_SITE_UPGRADE'),
				('MINOR_CIV_KABUL_TRAIT', 			'MINOR_CIV_KABUL_UNIT_EXPERIENCE_BONUS'),
				('MINOR_CIV_KUMASI_TRAIT', 			'MINOR_CIV_KUMASI_CULTURE_TRADE_ROUTE_YIELD_BONUS'),
				('MINOR_CIV_KUMASI_TRAIT', 			'MINOR_CIV_KUMASI_GOLD_TRADE_ROUTE_YIELD_BONUS'),
				('MINOR_CIV_LA_VENTA_TRAIT', 		'MINOR_CIV_LA_VENTA_CAN_COLLOSSAL_HEAD'),
				('MINOR_CIV_LISBON_TRAIT', 			'MINOR_CIV_LISBON_SEA_TRADE_ROUTE_PLUNDER_IMMUNITY_BONUS'),
				('MINOR_CIV_MOHENJO_DARO_TRAIT', 'MINOR_CIV_MOHENJO_DARO_CITIES_FRESHWATER_HOUSING_BONUS'),
				('MINOR_CIV_NAN_MADOL_TRAIT', 	'MINOR_CIV_NAN_MADOL_DISTRICTS_CULTURE_BONUS'),
				('MINOR_CIV_PRESLAV_TRAIT', 			'MINOR_CIV_PRESLAV_BARRACKS_STABLE_IDENTITY_BONUS'),
				('MINOR_CIV_PRESLAV_TRAIT', 			'MINOR_CIV_PRESLAV_ARMORY_IDENTITY_BONUS'),
				('MINOR_CIV_PRESLAV_TRAIT', 			'MINOR_CIV_PRESLAV_MILITARY_ACADEMY_IDENTITY_BONUS'),
				('MINOR_CIV_VALLETTA_TRAIT', 		'MINOR_CIV_VALLETTA_PURCHASE_CHEAPER_WALLS_BONUS'),
				('MINOR_CIV_VALLETTA_TRAIT', 		'MINOR_CIV_VALLETTA_PURCHASE_CHEAPER_CASTLE_BONUS'),
				('MINOR_CIV_VALLETTA_TRAIT', 		'MINOR_CIV_VALLETTA_PURCHASE_CHEAPER_STAR_BONUS'),
				('MINOR_CIV_VALLETTA_TRAIT', 		'MINOR_CIV_VALLETTA_CITY_CENTER_BUILDINGS_BONUS'),
				('MINOR_CIV_VALLETTA_TRAIT', 		'MINOR_CIV_VALLETTA_ENCAMPMENT_BUILDINGS_BONUS'),
				('MINOR_CIV_ZANZIBAR_TRAIT', 		'MINOR_CIV_ZANZIBAR_CINNAMON_RESOURCE_BONUS'),
				('MINOR_CIV_ZANZIBAR_TRAIT', 		'MINOR_CIV_ZANZIBAR_CLOVES_RESOURCE_BONUS');

--City-states benefit from traits DLC compatibility
INSERT INTO TraitModifiers 
			(TraitType, 									ModifierId)
SELECT 'MINOR_CIV_ARMAGH_TRAIT', 		'MINOR_CIV_ARMAGH_UNLOCK_MONASTERY_BONUS'
WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ARMAGH');

INSERT INTO TraitModifiers 
			(TraitType, 									ModifierId)
SELECT 'MINOR_CIV_AUCKLAND_TRAIT', 	'MINOR_CIV_AUCKLAND_SHALLOW_WATER_PRODUCTION_BONUS_BASE'
WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_AUCKLAND');

INSERT INTO TraitModifiers 
			(TraitType, 									ModifierId)
SELECT 'MINOR_CIV_AUCKLAND_TRAIT', 	'MINOR_CIV_AUCKLAND_SHALLOW_WATER_PRODUCTION_BONUS_INDUSTRIAL'
WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_AUCKLAND');

INSERT INTO TraitModifiers 
			(TraitType, 									ModifierId)
SELECT 'MINOR_CIV_GRANADA_TRAIT', 	'MINOR_CIV_GRANADA_UNLOCK_ALCAZAR_BONUS'
WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_GRANADA');

INSERT INTO TraitModifiers 
			(TraitType, 									ModifierId)
SELECT 'MINOR_CIV_MUSCAT_TRAIT', 		'MINOR_CIV_MUSCAT_COMMERCIAL_HUB_AMENITY_BONUS'
WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_MUSCAT');

INSERT INTO TraitModifiers 
			(TraitType, 									ModifierId)
SELECT 'MINOR_CIV_MUSCAT_TRAIT', 		'CVS_MINOR_CIV_MUSCAT_HIGH_ADJACENCY_AMENITY_UNIQUE_INFLUENCE_BONUS'
WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_MUSCAT');

INSERT INTO TraitModifiers 
			(TraitType, 									ModifierId)
SELECT 'MINOR_CIV_MUSCAT_TRAIT', 		'CVS_MINOR_CIV_MUSCAT_HIGH_ADJACENCY_AMENITY_BONUS'
WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_MUSCAT');

INSERT INTO TraitModifiers 
			(TraitType, 									ModifierId)
SELECT 'MINOR_CIV_PALENQUE_TRAIT', 	'MINOR_CIV_PALENQUE_CAMPUS_GROWTH_BONUS'
WHERE EXISTS (SELECT * FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PALENQUE');
		
--=========
--MODIFIERS
--=========
INSERT INTO Modifiers 
				(ModifierId, 														ModifierType, 															OwnerRequirementSetId, 						SubjectRequirementSetId)	
VALUES	('CVS_MINOR_CIV_FREE_ANCIENT_WALLS', 		'CVS_MINOR_CIV_GRANT_WALLS_IN_CITY_IGNORE', 	NULL, 													NULL),
				--('CVS_MINOR_CIV_FREE_MEDIEVAL_WALLS', 		'CVS_MINOR_CIV_GRANT_WALLS_IN_CITY_IGNORE', 	'CVS_MINOR_CIV_IN_MEDIEVAL_ERA', 	NULL),
				--('CVS_MINOR_CIV_FREE_RENAISSANCE_WALLS', 'CVS_MINOR_CIV_GRANT_WALLS_IN_CITY_IGNORE', 'CVS_MINOR_CIV_IN_RENAISSANCE_ERA', NULL),
				('CVS_MINOR_CIV_MUSCAT_HIGH_ADJACENCY_AMENITY_UNIQUE_INFLUENCE_BONUS',	'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', NULL, 'PLAYER_IS_SUZERAIN'),
				('CVS_MINOR_CIV_MUSCAT_HIGH_ADJACENCY_AMENITY_BONUS',	'CVS_MODIFIER_MUSCAT_PLAYER_CITIES_ADJUST_AMENITIES_FROM_CITY_STATES', NULL, 'CVS_MUSCAT_CITY_HAS_HIGH_ADJACENCY_COMMERCIAL_HUB_REQUIREMENTSET');

--==================
--MODIFIER ARGUMENTS
--==================
INSERT INTO ModifierArguments
				(ModifierId, 														Name, 				Value)
VALUES	('CVS_MINOR_CIV_FREE_ANCIENT_WALLS', 		'BuildingType', 	'BUILDING_WALLS'),
				--('CVS_MINOR_CIV_FREE_MEDIEVAL_WALLS', 		'BuildingType', 	'BUILDING_CASTLE'),
				--('CVS_MINOR_CIV_FREE_RENAISSANCE_WALLS', 'BuildingType', 	'BUILDING_STAR_FORT'),
				('CVS_MINOR_CIV_MUSCAT_HIGH_ADJACENCY_AMENITY_UNIQUE_INFLUENCE_BONUS', 'ModifierId', 'CVS_MINOR_CIV_MUSCAT_HIGH_ADJACENCY_AMENITY_BONUS'),
				('CVS_MINOR_CIV_MUSCAT_HIGH_ADJACENCY_AMENITY_BONUS', 'Amount', 1);

--============
--REQUIREMENTS
--============
--RequirementSets
INSERT INTO RequirementSets
				(RequirementSetId, 									RequirementSetType)
VALUES	('CVS_MINOR_CIV_IN_MEDIEVAL_ERA', 		'REQUIREMENTSET_TEST_ALL'),
				('CVS_MINOR_CIV_IN_RENAISSANCE_ERA', 'REQUIREMENTSET_TEST_ALL'),
				('CVS_MUSCAT_CITY_HAS_HIGH_ADJACENCY_COMMERCIAL_HUB_REQUIREMENTSET', 'REQUIREMENTSET_TEST_ANY');

--RequirementSetRequirements
INSERT INTO RequirementSetRequirements
				(RequirementSetId,									 RequirementId)
VALUES	('CVS_MINOR_CIV_IN_MEDIEVAL_ERA', 		'CVS_REQUIRES_MINOR_CIV_IN_MEDIEVAL_ERA'),
				('CVS_MINOR_CIV_IN_RENAISSANCE_ERA', 'CVS_REQUIRES_MINOR_CIV_IN_RENAISSANCE_ERA'),
				('CVS_MUSCAT_CITY_HAS_HIGH_ADJACENCY_COMMERCIAL_HUB_REQUIREMENTSET', 'CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_COMMERCIAL_HUB');

INSERT INTO RequirementSetRequirements
				(RequirementSetId,																			RequirementId)
SELECT	'CVS_MUSCAT_CITY_HAS_HIGH_ADJACENCY_COMMERCIAL_HUB_REQUIREMENTSET',	'CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_'||CivUniqueDistrictType
FROM DistrictReplaces
WHERE ReplacesDistrictType = 'DISTRICT_COMMERCIAL_HUB';

--Requirements
INSERT INTO Requirements
				(RequirementId, 															RequirementType)
VALUES	('CVS_REQUIRES_MINOR_CIV_IN_MEDIEVAL_ERA',			'REQUIREMENT_PLAYER_ERA_AT_LEAST'),
				('CVS_REQUIRES_MINOR_CIV_IN_RENAISSANCE_ERA', 	'REQUIREMENT_PLAYER_ERA_AT_LEAST'),
				('CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_COMMERCIAL_HUB', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT');

INSERT INTO Requirements
				(RequirementId,																							RequirementType)
SELECT	'CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_'||CivUniqueDistrictType,		'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'
FROM DistrictReplaces
WHERE ReplacesDistrictType = 'DISTRICT_COMMERCIAL_HUB';

--RequirementArguments
INSERT INTO RequirementArguments
				(RequirementId, 															Name, 		Value)
VALUES	('CVS_REQUIRES_MINOR_CIV_IN_MEDIEVAL_ERA', 		'EraType', 	'ERA_MEDIEVAL'),
				('CVS_REQUIRES_MINOR_CIV_IN_RENAISSANCE_ERA', 	'EraType', 	'ERA_RENAISSANCE'),
				('CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_COMMERCIAL_HUB', 'DistrictType', 'DISTRICT_COMMERCIAL_HUB'),
				('CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_COMMERCIAL_HUB', 'YieldType', 'YIELD_GOLD'),
				('CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_COMMERCIAL_HUB', 'Amount', 4);

INSERT INTO RequirementArguments
				(RequirementId,																						Name,				Value)
SELECT	'CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_'||CivUniqueDistrictType,	'DistrictType',	CivUniqueDistrictType
FROM DistrictReplaces
WHERE ReplacesDistrictType = 'DISTRICT_COMMERCIAL_HUB';
INSERT INTO RequirementArguments
				(RequirementId,																						Name,			Value)
SELECT	'CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_'||CivUniqueDistrictType,	'YieldType',	'YIELD_SCIENCE'
FROM DistrictReplaces
WHERE ReplacesDistrictType = 'DISTRICT_COMMERCIAL_HUB';
INSERT INTO RequirementArguments
				(RequirementId,																						Name,		Value)
SELECT	'CVS_MUSCAT_REQUIRES_HIGH_ADJACENCY_'||CivUniqueDistrictType,	'Amount',	4
FROM DistrictReplaces
WHERE ReplacesDistrictType = 'DISTRICT_COMMERCIAL_HUB';

--=============================
-- CITY-STATE BIASES -- VANILLA
--=============================
--========================
-- Core
--========================
INSERT INTO StartBiasTerrains
		(CivilizationType,					TerrainType,				Tier	)
VALUES	('CIVILIZATION_BRUSSELS',			'TERRAIN_GRASS',			5		),
		('CIVILIZATION_BRUSSELS',			'TERRAIN_GRASS_HILLS',		5		),
		('CIVILIZATION_CARTHAGE',			'TERRAIN_COAST',			1		),
		('CIVILIZATION_CARTHAGE',			'TERRAIN_OCEAN',			1		),
		('CIVILIZATION_GENEVA',				'TERRAIN_GRASS_MOUNTAIN',	3		),
		('CIVILIZATION_GENEVA',				'TERRAIN_PLAINS_MOUNTAIN',	3		),
		('CIVILIZATION_HATTUSA',			'TERRAIN_GRASS_HILLS',		5		),
		('CIVILIZATION_HATTUSA',			'TERRAIN_PLAINS_HILLS',		5		),
		('CIVILIZATION_JERUSALEM',			'TERRAIN_DESERT',			3		),
		('CIVILIZATION_JERUSALEM',			'TERRAIN_DESERT_HILLS',		3		),
		('CIVILIZATION_KABUL',				'TERRAIN_PLAINS_HILLS',		5		),
		('CIVILIZATION_KABUL',				'TERRAIN_DESERT_HILLS',		5		),
		('CIVILIZATION_KABUL',				'TERRAIN_PLAINS',			5		),
		('CIVILIZATION_KABUL',				'TERRAIN_DESERT',			5		),
		('CIVILIZATION_KANDY',				'TERRAIN_GRASS_HILLS',		5		),	
		('CIVILIZATION_KUMASI',				'TERRAIN_GRASS',			5		),	
		('CIVILIZATION_KUMASI',				'TERRAIN_GRASS_HILLS',		5		),	
		('CIVILIZATION_MOHENJO_DARO',		'TERRAIN_GRASS',			5		),
		('CIVILIZATION_MOHENJO_DARO',		'TERRAIN_GRASS_HILLS',		5		),
		('CIVILIZATION_MOHENJO_DARO',		'TERRAIN_PLAINS_HILLS',		5		),
		('CIVILIZATION_PRESLAV',			'TERRAIN_GRASS_HILLS',		5		),
		('CIVILIZATION_PRESLAV',			'TERRAIN_PLAINS_HILLS',		5		),
		('CIVILIZATION_VALLETTA',			'TERRAIN_GRASS_HILLS',		5		),
		('CIVILIZATION_VALLETTA',			'TERRAIN_PLAINS_HILLS',		5		),
		('CIVILIZATION_VILNIUS',			'TERRAIN_GRASS',			5		),
		('CIVILIZATION_VILNIUS',			'TERRAIN_PLAINS',			5		),
		('CIVILIZATION_YEREVAN',			'TERRAIN_GRASS_MOUNTAIN',	3		),
		('CIVILIZATION_YEREVAN',			'TERRAIN_PLAINS_MOUNTAIN',	3		),
		('CIVILIZATION_ZANZIBAR',			'TERRAIN_COAST',			1		),
		('CIVILIZATION_ZANZIBAR',			'TERRAIN_OCEAN',			1		),
		('CIVILIZATION_BUENOS_AIRES',		'TERRAIN_COAST',			2		),
		('CIVILIZATION_HONG_KONG',			'TERRAIN_COAST',			2		),
		('CIVILIZATION_JAKARTA',			'TERRAIN_COAST',			2		),
		('CIVILIZATION_LISBON',				'TERRAIN_COAST',			1		), -- MARITIME
		('CIVILIZATION_NAN_MADOL',			'TERRAIN_COAST',			2		),
		('CIVILIZATION_STOCKHOLM',			'TERRAIN_COAST',			2		),
		('CIVILIZATION_TORONTO',			'TERRAIN_COAST',			2		),
		('CIVILIZATION_VALLETTA',			'TERRAIN_COAST',			2		),
		('CIVILIZATION_ANTIOCH',			'TERRAIN_GRASS_MOUNTAIN',	3		),
		('CIVILIZATION_ANTIOCH',			'TERRAIN_PLAINS_MOUNTAIN',	3		),
		('CIVILIZATION_BABYLON',			'TERRAIN_DESERT',			3		);
	
INSERT INTO StartBiasResources
		(CivilizationType,					ResourceType,			Tier	)
VALUES	('CIVILIZATION_LISBON',				'RESOURCE_FISH',		1		), -- MARITIME
		('CIVILIZATION_LISBON',				'RESOURCE_CRABS',		1		), -- MARITIME
		('CIVILIZATION_NAN_MADOL',			'RESOURCE_FISH',		1		), -- MARITIME
		('CIVILIZATION_NAN_MADOL',			'RESOURCE_CRABS',		1		); -- MARITIME
		
INSERT INTO StartBiasFeatures
		(CivilizationType,					FeatureType,			Tier	)
VALUES	('CIVILIZATION_BRUSSELS',			'FEATURE_MARSH',		3		),
		('CIVILIZATION_BRUSSELS',			'FEATURE_FOREST',		5		),
		('CIVILIZATION_HONG_KONG',			'FEATURE_JUNGLE',		5		),
		('CIVILIZATION_JAKARTA',			'FEATURE_JUNGLE',		5		),
		('CIVILIZATION_JERUSALEM',			'FEATURE_DEAD_SEA',		3		),
		('CIVILIZATION_KANDY',				'FEATURE_MARSH',		5		),
		('CIVILIZATION_KANDY',				'FEATURE_JUNGLE',		5		),
		('CIVILIZATION_KUMASI',				'FEATURE_JUNGLE',		3		),
		('CIVILIZATION_LA_VENTA',			'FEATURE_JUNGLE',		3		),
		('CIVILIZATION_NAN_MADOL',			'FEATURE_JUNGLE',		5		),
		('CIVILIZATION_PRESLAV',			'FEATURE_FOREST',		5		),
		('CIVILIZATION_STOCKHOLM',			'FEATURE_FOREST',		5		),
		('CIVILIZATION_TORONTO',			'FEATURE_FOREST',		5		),
		('CIVILIZATION_VILNIUS',			'FEATURE_FOREST',		5		),
		('CIVILIZATION_BABYLON',			'FEATURE_FLOODPLAINS',	3		);
--========================
-- DLC
--========================
-- Auckland
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,		Tier)
SELECT	'CIVILIZATION_AUCKLAND',		'TERRAIN_COAST',	1
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_AUCKLAND');
INSERT INTO StartBiasFeatures
		(CivilizationType,				FeatureType,		Tier)
SELECT	'CIVILIZATION_AUCKLAND',		'FEATURE_FOREST',	5
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_AUCKLAND');
INSERT INTO StartBiasResources
		(CivilizationType,				ResourceType,		Tier)
SELECT	'CIVILIZATION_AUCKLAND',		'RESOURCE_FISH',	1
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_AUCKLAND');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_AUCKLAND',		'TERRAIN_OCEAN',	1
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_AUCKLAND');

--Antananarivo
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_ANTANANARIVO',	'TERRAIN_GRASS_HILLS',	1
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ANTANANARIVO');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_ANTANANARIVO',	'TERRAIN_PLAINS_HILLS',	1
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ANTANANARIVO');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_ANTANANARIVO',	'TERRAIN_GRASS',		2
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ANTANANARIVO');
INSERT INTO StartBiasRivers
		(CivilizationType,										Tier)
SELECT	'CIVILIZATION_ANTANANARIVO',							3
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ANTANANARIVO');
INSERT INTO StartBiasResources
		(CivilizationType,				ResourceType,			Tier)
SELECT	'CIVILIZATION_ANTANANARIVO',	'RESOURCE_RICE',		4
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ANTANANARIVO');

--Armagh
INSERT INTO StartBiasFeatures
		(CivilizationType,				FeatureType,			Tier)
SELECT	'CIVILIZATION_ARMAGH',			'FEATURE_FOREST',		1
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ARMAGH');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_ARMAGH',			'TERRAIN_GRASS',		2
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ARMAGH');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_ARMAGH',			'TERRAIN_GRASS_HILLS',	3
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ARMAGH');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_ARMAGH',			'TERRAIN_PLAINS_HILLS',	3
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ARMAGH');
INSERT INTO StartBiasResources
		(CivilizationType,				ResourceType,			Tier)
SELECT	'CIVILIZATION_ARMAGH',			'RESOURCE_STONE',		4
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_ARMAGH');

--Granada
INSERT INTO StartBiasRivers
		(CivilizationType,										Tier)
SELECT	'CIVILIZATION_GRANADA',									1
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_GRANADA');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,				Tier)
SELECT	'CIVILIZATION_GRANADA',			'TERRAIN_GRASS_MOUNTAIN',	2
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_GRANADA');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,				Tier)
SELECT	'CIVILIZATION_GRANADA',			'TERRAIN_PLAINS_MOUNTAIN',	2
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_GRANADA');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_GRANADA',			'TERRAIN_PLAINS_HILLS',	3
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_GRANADA');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_GRANADA',			'TERRAIN_GRASS_HILLS',	3
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_GRANADA');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_GRANADA',			'TERRAIN_COAST',		4
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_GRANADA');

--Muscat
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_MUSCAT',			'TERRAIN_COAST',		1
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_MUSCAT');
INSERT INTO StartBiasResources
		(CivilizationType,				ResourceType,			Tier)
SELECT	'CIVILIZATION_MUSCAT',			'RESOURCE_FISH',		2
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_MUSCAT');
INSERT INTO StartBiasResources
		(CivilizationType,				ResourceType,			Tier)
SELECT	'CIVILIZATION_MUSCAT',			'RESOURCE_CRABS',		2
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_MUSCAT');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_MUSCAT',			'TERRAIN_PLAINS_HILLS',	3
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_MUSCAT');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_MUSCAT',			'TERRAIN_DESERT_HILLS',	3
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_MUSCAT');

--Palenque
INSERT INTO StartBiasFeatures
		(CivilizationType,				FeatureType,			Tier)
SELECT	'CIVILIZATION_PALENQUE',		'FEATURE_JUNGLE',		1
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PALENQUE');
INSERT INTO StartBiasRivers
		(CivilizationType,										Tier)
SELECT	'CIVILIZATION_PALENQUE',								2
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PALENQUE');
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,			Tier)
SELECT	'CIVILIZATION_PALENQUE',		'TERRAIN_GRASS',		3
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PALENQUE');
INSERT INTO StartBiasFeatures
		(CivilizationType,				FeatureType,			Tier)
SELECT	'CIVILIZATION_PALENQUE',		'FEATURE_MARSH',		4
WHERE EXISTS (SELECT CivilizationType FROM Civilizations WHERE CivilizationType = 'CIVILIZATION_PALENQUE');